Created an option to find modules via identifiers
InverterNetwork/contracts pull request #327
Opened 2023-08-15 08:21 UTC by saxenism

As a fix for the issue mentioned by the auditors in issue #317 regarding the `findModuleAddressInOrchestrator` not designed to handle the cases where multiple modules with the same name are being used, I have made a few changes to `findModuleAddressInOrchestrator`.

Since the URL of a module is much less likely to be the same as other modules, I have replaced the query string from the module title to the module URL.

And since, it is technically possible to have multiple modules with the same URL, i have also given an option to search for module address using a **unique module identifier**.

2023-08-17 13:34 UTC, FHieser commented
![Where tests](https://github.com/InverterNetwork/inverter-contracts/assets/47272854/5097b397-da67-4b43-9b93-1daf3b6042d8)

2023-08-17 13:35 UTC, FHieser requested changes

2023-08-17 13:35 UTC, FHieser commented on src/orchestrator/Orchestrator.sol
The tests are missing

2023-08-18 09:02 UTC, saxenism commented on src/orchestrator/Orchestrator.sol
![image](https://github.com/InverterNetwork/inverter-contracts/assets/32522659/3493482b-0718-4986-a918-59431b52f76a)

The tests are no longer missing 👉👈

2023-08-18 09:04 UTC, saxenism commented
Considering this comment:
![](https://user-images.githubusercontent.com/82726722/258984044-2ede1952-45e6-491f-9474-f84a1b3d62e6.png)

Added the documentation for `dependencyData`.

The `dependencyData` now expects 3 fields:
1. bool hasDependency: True if dependencies are expected, false otherwise
2. string[] dependenciesURLs: URL of the modules that can be counted as dependencies
3. bytes additionalData: Any additional data that you might want access to, inside of `init2`.

2023-12-07 14:47 UTC, FHieser commented
The changes will be implemented with the #371 PR

2023-12-07 14:47 UTC, closed without merging