Remove _ensureTokenBalance checks when adding payment Orders and refactor triggerFor()
InverterNetwork/contracts pull request #332
Opened 2023-08-16 21:54 UTC by 0xNuggan

closes #324

2023-08-17 07:06 UTC, FHieser requested changes

2023-08-17 07:06 UTC, FHieser commented on lib/forge-std
Why are you updating the submodules here?

2023-08-17 07:06 UTC, FHieser commented on src/modules/logicModule/paymentClient/ERC20PaymentClient.sol
>          _outstandingTokenAmount += totalTokenAmount;
totalAmount is not necessary anymore here

2023-08-17 07:06 UTC, FHieser commented on src/modules/logicModule/RecurringPaymentManager.sol
>              ++index;
Everything above this (up to line 234) is not necessary anymore

2023-08-17 07:07 UTC, FHieser commented on src/modules/logicModule/paymentClient/ERC20PaymentClient.sol
Also _ensureTokenBalance didnt get changed to just add tokens to the contracts

2023-08-17 07:18 UTC, FHieser commented on src/modules/logicModule/paymentClient/ERC20PaymentClient.sol
>          _outstandingTokenAmount += totalTokenAmount;
Forget what I said here

2023-08-17 08:11 UTC, 0xNuggan commented on src/modules/logicModule/paymentClient/ERC20PaymentClient.sol
As I understood it, since we are now checking _ensureTokenBalance at the time of processing the orders (and starting the payout), there was no need to remove the (amount > balance ) check, and that way we still keep the possibility of using available funds (from f.ex. cancellations). Example
-PaymentOrder A gets added, amount: 50. No funds are pulled
-PaymentOrder B gets added, amount: 100. no funds are pulled
-PaymentOrders get Processed: _ensureTokenBalance of 150 gets called, and the 150 tokens get pulled
---> **IF** there already were 75 tokens from a cancellation/refund/whatever, we'd only need to call _ensureTokenBalance with 75.

2023-08-17 08:27 UTC, FHieser commented on src/modules/logicModule/paymentClient/ERC20PaymentClient.sol
Yeah
That would be in case we want to drain the contract of unnecessary funds, that found their way there for some reason
But in case we would like to use the "reserve" functionality of the ensureTokenBalance that was initially proposed, this would not work
I think we should stick to the changing it to its original intended purpose

2023-08-18 11:13 UTC, FHieser approved these changes

2023-08-18 14:51 UTC, merged