Bonding curve extra scripts
InverterNetwork/contracts pull request #355
Opened 2023-10-13 13:33 UTC by 0xNuggan

Ties into #308 I guess, but is separate. This deploys an Investable Workstream in the type wanted by the BCRG

2024-02-13 11:57 UTC, Zitzak commented
What should we do with this issue PR @0xNuggan ? Maybe close it for now, as it has been open for a while

2024-02-29 09:42 UTC, Zitzak requested changes
First time I reviewed/took a good look at the script. Think I caught most things but if we want to be more sure then we might want to request review from someone else as well
@0xNuggan

2024-02-29 09:42 UTC, Zitzak commented on script/deployment/DeploymentScript.s.sol
> +        "BancorVirtualSupplyBondingCurveFundingManager"
Should this URL be accessible?  It not pointing anywhere atm

2024-02-29 09:42 UTC, Zitzak commented on script/utils/InvestableWorkstreams/01-DeployInvestableWorkstream.s.sol
> +//import {ERC20Mock} from "test/utils/mocks/ERC20Mock.sol";
Not being used. Same for the line beneath it. Could be removed

2024-02-29 09:42 UTC, Zitzak commented on script/utils/InvestableWorkstreams/01-DeployInvestableWorkstream.s.sol
> +    BancorFormula formula = BancorFormula(bancorFormulaAddress);
Curious if we store the address in the `.env` file manually or do we export them?

2024-02-29 09:42 UTC, Zitzak commented on script/utils/InvestableWorkstreams/01-DeployInvestableWorkstream.s.sol
> +                abi.encode(
The contract expect 2 objects and 1 token address, as well as the decimals of the issuance token. [See link](https://github.com/InverterNetwork/inverter-contracts/blob/dev/test/modules/fundingManager/bondingCurveFundingManager/BancorVirtualSupplyBondingCurveFundingManager.t.sol#L163)

2024-02-29 09:42 UTC, Zitzak commented on script/utils/InvestableWorkstreams/01-DeployInvestableWorkstream.s.sol
> +            abi.encode(orchestratorOwner, orchestratorOwner),
Are we expecting the Owner to have also the Manager role here?

2024-02-29 09:42 UTC, Zitzak commented on script/utils/giveBountyManagerRolesToAddress.s.sol
> +    address bountyManagerAddress = address(0); // Introduce deployed bounty manager address here
Should this also be taken from the `.env` files as with all the other addresses? Or will the flow be such that who ever executes this script will do so while editing the script?

2024-02-29 09:42 UTC, Zitzak commented on script/utils/giveBountyManagerRolesToAddress.s.sol
> +    address bountyManagerAddress = address(0); // Introduce deployed bounty manager address here
Same for the other addresses in this script

2024-02-29 15:04 UTC, 0xNuggan commented on script/deployment/DeploymentScript.s.sol
> +        "BancorVirtualSupplyBondingCurveFundingManager"
Yeah, we did some example links ages ago as placeholder. It's about time to change them to the real ones, I'll open an issue for it.

2024-02-29 15:09 UTC, 0xNuggan commented on script/utils/InvestableWorkstreams/01-DeployInvestableWorkstream.s.sol
> +            abi.encode(orchestratorOwner, orchestratorOwner),
Yes, that is correct

2024-02-29 16:34 UTC, 0xNuggan commented
Thanks for the review! I've clarified the .env stuff. Basically it goes: If the address exists, it should be specified in the env file and used from there. If the contract doesn't exist, you can uncomment the corresponding part in the script to deploy it on the go.

Thanks for the heads up with the initial config. Not sure what happened there, since we deployed the curve already a couple times :thinking:

2024-03-05 11:37 UTC, Zitzak requested changes
There is still an issue with the way the init is done in the Bonding Curve Funding Manager

2024-03-05 11:37 UTC, Zitzak commented on script/utils/InvestableWorkstreams/01-DeployInvestableWorkstream.s.sol
> +                abi.encode(
I don't think this works, as the BondingCurveFundingManager expects 3 different objects

2024-03-13 10:10 UTC, 0xNuggan commented
If you uncommented line 85 it worked though! Anyway, I changed it to send the objects, it's cleaner :)

2024-03-14 09:31 UTC, Zitzak approved these changes
LGTM

2024-03-14 09:32 UTC, Zitzak commented
Ohw interesting. Didn't expect that it would work. Do you know why that is? Doesn't it just expect objects? @0xNuggan

2024-03-14 10:04 UTC, 0xNuggan commented
I think since it is a struct it just reads the storage in the expected chunks? Anyway, it's definitely better to be explicit :)

2024-03-14 14:15 UTC, merged