Create digest helper function for meta tx forwarder
InverterNetwork/contracts pull request #430
Opened 2024-03-06 15:24 UTC by FHieser

This solves this issue
https://linear.app/inverter/issue/SC-198/create-digest-helper-function-for-metatx-forwarder

2024-03-08 14:06 UTC, marvinkruse approved these changes
Looks good to me!

2024-03-12 02:37 UTC, Zitzak requested changes
Found only one small thing. Otherwise looks good!

2024-03-12 02:37 UTC, Zitzak commented on src/external/forwarder/TransactionForwarder.sol
> +    function getStructHash(ERC2771Forwarder.ForwardRequestData memory req)
Should have an underscore to keep internal function convention

2024-03-12 08:34 UTC, FHieser commented on src/external/forwarder/TransactionForwarder.sol
> +    function getStructHash(ERC2771Forwarder.ForwardRequestData memory req)
@Zitzak added it accordingly
Will merge with the approve of Marvin K

2024-03-12 08:47 UTC, merged