Chore/rename contracts
InverterNetwork/contracts pull request #454
Opened 2024-04-19 09:01 UTC by Zitzak

## What has been done
- Updated contract Natspecs
- Added `interfaces` folder whenever I project more contracts to be created within the specific category/directory
- Moved `beacons` from the `factories` folder to src/. Same for the test files
    - I followed the example of how the scripts directory was structured. Made more sense to me
- I’ve appended `base` to each abstract contract to signal they are base and not implementation contracts
  - Exception for the rebasing token base contracts
- Aligned all the imports for the contracts so the order is the same
  1. Internal Interfaces
  2. Internal Dependencies
  3. External Interfaces
  4. External Dependencies
- Updated all the error for each contract to match new naming
- Add remapping for the main module categories
- Removed the wording `FundingManager` from the base contracts
- Moved libraries within the module directory which where in sub-directories to the shared lib folder
- All of current Logic Modules (LM) are Payment Clients (PC), and they all use ERC20, which is why I moved them together in the same directory

[Link to google sheet where I kept track of name changes and categorisations can be found here](https://docs.google.com/spreadsheets/d/1mAzfiNHalK0CNJEMYIraWuffmmEDgTvRz1TdcNSEkvA/edit#gid=0)

## Open Questions
- We have a singleVoteGovernor and a normal Governor now, which are two completely different use cases. Maybe rename to InverterGovernor?
- Do we have events where we need it to reconstruct the state off-chain?
- How to structure the directory of the Payment Processor
- What to do about the Utils folder?

## Sporadic Errors
### Governor
Failed amount: 3 times
``` 
Encountered 1 failing test in test/external/Governor_v1.t.sol:GovernorV1Test
[FAIL. Reason: call reverted as expected, but without data; counterexample: calldata=0x443a5b3800000000000000000000000000000000000000000000000000000000000003980000000000000000000000004e59b44847b379578588920ca78fbf26c0b4956c args=[920, 0x4e59b44847b379578588920cA78FbF26c0B4956C]] testAccessibleBeacon(uint256,address) (runs: 2, μ: 26877, ~: 26877)
```
### SingleVoteGovernor
Failed amount: 1 time
```
Encountered 1 failing test in test/modules/SingleVoteGovernor.t.sol:SingleVoteGovernorTest
[FAIL. Reason: call did not revert as expected; counterexample: calldata=0xcaf8d2b30000000000000000000000007fa9385be102ac3eac297483dd6233d62b3e1496 args=[0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496]] testOnlyGovernanceIsAuthorized(address) (runs: 102, μ: 38682, ~: 38682)
```

2024-04-19 12:19 UTC, FHieser requested changes
First of:
Props to you @Zitzak 
This was huuuuge. Thanks for doing that.

I added some comments for the descriptions of the contract. Some of them were a bit outdated, but that wasnt your doing.

One thing that might take some time for me getting used to is probably the error naming stuff. Especially the adding of Module__ before every error i found a bit over the top. But i think for now this is fine, we can tackle this at a later point of time too.

2024-04-19 12:19 UTC, FHieser commented on script/proxies/UpgradeInverterBeacon_v1.sol
you changed it so that this is not a script anymore
Add the .s. in the naming

2024-04-19 12:19 UTC, FHieser commented on script/utils/InvestableWorkstreams/01-DeployInvestableWorkstream.s.sol
> +} from "@fm/bondingCurve/FM_BC_Bancor_Redeeming_VirtualSupply_v1.sol";
Nice :D

2024-04-19 12:19 UTC, FHieser commented on src/external/governance/Governor_v1.sol
> + * @notice  This contract manages upgrades to beacon contracts through role-based permissions,
I would reorder this
* @notice This contract manages various administrative functions that can be executed only by specified multisig addresses. It supports upgrades to beacon contracts through role-based permissions, enabling a timelocked upgrade process and emergency procedures.

2024-04-19 12:19 UTC, FHieser commented on src/external/governance/interfaces/IGovernor_v1.sol
> +    error Governor_v1__InvalidAddress(address adr);
I think changing the naming of the error messages to include the version might be debatable
Its probably due to the Replace functionality you used, but I think it comes with pros and cons
Due to the time constraints I would recommend to keep it that way for now, but I think we might wanna talk about this

2024-04-19 12:19 UTC, FHieser commented on src/factories/ModuleFactory_v1.sol
> + *          Provides management functionality to govern module behavior and interactions.
~~Provides management functionality to govern module behavior and interactions.~~
-> Allows for configuration of modules starting state via provided deployment data.

2024-04-19 12:19 UTC, FHieser commented on src/factories/interfaces/IModuleFactory_v1.sol
> +    /// @notice Returns the governor_v1 contract address
~~governor_v1~~
-> governor

2024-04-19 12:19 UTC, FHieser commented on src/factories/interfaces/IOrchestratorFactory_v1.sol
> +    /// @notice Event emitted when a new orchestrator_v1 is created.
seems like the naming in the @notice tends to be <contract>_v1
Seems kind of weird to me?
@Zitzak You decide. We can probably can also tackle this later
In case we want to change this, the easiest way to find this is probably regex:
Something like this->  /// @notice*_v1

2024-04-19 12:19 UTC, FHieser commented on src/modules/authorizer/IAuthorizer_v1.sol
> +    error Module__Authorizer_v1__NotActiveModule(address module);
Why was this Modul__ somthing in the first place?

2024-04-19 12:19 UTC, FHieser commented on src/modules/base/Module_v1.sol
>   *
This Contract is the basic building block for all Modules in the Inverter Network.
It contains references to other contracts, modifier for access restriction, metadata to identify the module type as well as utility functions for general module interactions.

2024-04-19 12:19 UTC, FHieser commented on src/modules/base/Module_v1.sol
> + *          Using proxy contracts, e.g. beacons, enables globally updating module
~~Using proxy contracts, e.g. beacons, enables globally updating module~~
~~instances when its minor version changes, but supports differentiating~~
~~otherwise equal modules with different major versions.~~

2024-04-19 12:19 UTC, FHieser commented on src/modules/utils/SingleVoteGovernor_v1.sol
title notice and so forth missing

2024-04-19 12:19 UTC, FHieser commented on tasks/deployBaseContracts.sh
Just out of Interest:
@InverterNetwork/smart-contract-devs what does this contract do?

2024-04-19 12:19 UTC, FHieser commented on src/orchestrator/Orchestrator_v1.sol
> + * @dev     A new funding primitive to enable multiple actors within a decentralized
This Contract is the center and connecting block of all Modules in a Inverter Network Workflow.
It contains references to the essential contracts that make up a workflow.
By inheriting the ModuleManager it allows for managing which modules make up the workflow.

2024-04-19 12:19 UTC, FHieser commented on src/orchestrator/abstracts/ModuleManagerBase_v1.sol
> + * @dev     A contract to manage modules that can execute transactions via this
A contract to manage Inverter Network modules.
It allows for adding and removing modules in a local registry for reference.
Additional functionality includes the execution of calls from this contract.

2024-04-19 12:19 UTC, FHieser commented on src/orchestrator/abstracts/ModuleManagerBase_v1.sol
> + *          contract and manage own role-based access control mechanisms.
~~A contract to manage modules that can execute transactions via this~~
~~contract and manage own role-based access control mechanisms.~~

~~The role-based access control mechanism is based on OpenZeppelin's~~
~~AccessControl contract. Each module has it's own access control context~~
~~which it is able to freely manage.~~

2024-04-19 12:26 UTC, marvinkruse commented on tasks/deployBaseContracts.sh
I have no idea and never used it, I use the scripts. @0xNuggan do you use this or could we get rid of it?

2024-04-19 12:41 UTC, marvinkruse commented
Some notes from my review:

---

**Payment Clients**
To me, the structure here feels like it's overengineered:
* `src/modules/logicModule/paymentClient/ERC20PaymentClient/LM_PC_Bounty_v1.sol`
* `src/modules/logicModule/paymentClient/ERC20PaymentClient/LM_PC_Recurring_v1.sol`
I understand these are all payment clients and we wanna show that maybe, even if I think the whole `PC`/paymentClient part is redundant in itself as it doesn't reeeaaallly matter, but why not just simplify it like this:
* `src/modules/logicModule/LM_PC_Bounty_v1.sol`

This tells you that it's a logic module and a payment client. There is no need to separate the "non-payment-client" logic modules, as we don't have any anyways for now. Even if we did, I think they could be in the same folder. Like so:
* `src/modules/logicModule/LM_PC_Bounty_v1.sol`
* `src/modules/logicModule/LM_PC_Recurring_v1.sol`
* `src/modules/logicModule/LM_IPFSManager_v1.sol`
* `src/modules/logicModule/LM_PC_NFTGenerator_v1.sol`

I feel like having two subfolders that both tell you it's a payment client is a bit much. I know we might need to distinguish between `ERC20PaymentClient` and `ERC721PaymentClient` or whatnot in the future, but I feel like having that in the contract name is enough for now. If we have many of them at some point, we can still change the folder structure in the future, as it doesn't matter as much as the contract name.

---

**RecurringPaymentManager**
I know I might be alone here, but I don't feel like this is named well with `LM_PC_Recurring_v1.sol`.
Recurring-what? I felt like `RecurringPaymentManager` was a good enough name. We want to capture the essence of the contracts. This one is about creating and managing recurring payments. 

---

**BountyManager**
To me, calling it just `LM_PC_Bounty_v1.sol` seems a bit too simplified, but might just be me. I liked `BountyManager` (so `LM_PC_BountyManager_v1.sol`) because the contract is not just about "a bounty" (whatever that may mean) but about creating and claiming these. I feel like `BountyManager` captured that quite well. Happy to be proven wrong, though 😁

---

Thoughts from you guys @Zitzak @FHieser @0xNuggan?

2024-04-19 12:43 UTC, marvinkruse commented on src/external/governance/interfaces/IGovernor_v1.sol
> +    error Governor_v1__InvalidAddress(address adr);
Yeah, in general I would just change the name of the contract itself, not errors or events or whatever. If it's not possible time-wise I agree that we can just keep it like that and have a separate PR in the future to fix this, as it's not introducing any logic changes.

2024-04-19 12:44 UTC, marvinkruse commented on src/factories/interfaces/IOrchestratorFactory_v1.sol
> +    /// @notice Event emitted when a new orchestrator_v1 is created.
I would also not reference the version here, like I said above: basically only in the contract name. it's still the "orchestrator", doesn't really matter which version.

2024-04-19 12:49 UTC, 0xNuggan commented on script/utils/InvestableWorkstreams/01-DeployInvestableWorkstream.s.sol
> +} from "@fm/bondingCurve/FM_BC_Bancor_Redeeming_VirtualSupply_v1.sol";
yeah huge props on that

2024-04-19 12:52 UTC, 0xNuggan commented on tasks/deployBaseContracts.sh
Never used it. We can get rid of it

2024-04-19 12:54 UTC, marvinkruse commented on script/utils/InvestableWorkstreams/01-DeployInvestableWorkstream.s.sol
> +} from "@fm/bondingCurve/FM_BC_Bancor_Redeeming_VirtualSupply_v1.sol";
so much better :D

2024-04-19 13:05 UTC, FHieser commented on tasks/deployBaseContracts.sh
Yeah lets remove it

2024-04-19 13:45 UTC, 0xNuggan commented on src/external/governance/interfaces/IGovernor_v1.sol
> +    error Governor_v1__InvalidAddress(address adr);
Agree. Let's push it to the "non-logic-cleanup" bin :grin:

2024-04-19 13:47 UTC, 0xNuggan commented
Agree with @marvinkruse  on his points

2024-04-19 16:22 UTC, Zitzak commented
@FHieser in regard to the `Module__` for error strings, I actually came across it is some interfaces and others not. So I decided to go this route, but apparently this was a practice which was done in the past already.

I don't think this PR will be added today anymore. Who votes that this should be changed again? (react with thumbs up or down)
@marvinkruse @FHieser @0xNuggan

2024-04-19 16:27 UTC, Zitzak commented
In regard to the naming of the `LM_PC_Bounty_v1.sol` and `LM_PC_Recurring_v1.sol` contracts, I do agree that they don't look as nice as the full names. However if we decide on a naming convention then I think we should stick with it. Otherwise it will be back to personal preference again. Also, currently there is only one of these contract, but how to deal with it if more "Bounty" using LM will be written. We decided on the current scheme to make it future proof.

Lastly, the full name is still int the contract natspec.

Let's do another vote on this one with thumb up or down.

2024-04-19 16:34 UTC, Zitzak commented on src/external/governance/interfaces/IGovernor_v1.sol
> +    error Governor_v1__InvalidAddress(address adr);
So I actually did it on purpose, as I through it might be valuable information. Will change it back

2024-04-19 16:35 UTC, Zitzak commented on src/external/governance/interfaces/IGovernor_v1.sol
> +    error Governor_v1__InvalidAddress(address adr);
Also just seeing that I haven't added `Module__` for these errors (see questions below)

2024-04-19 16:51 UTC, Zitzak commented on src/modules/authorizer/IAuthorizer_v1.sol
> +    error Module__Authorizer_v1__NotActiveModule(address module);
See my message here
https://github.com/InverterNetwork/inverter-contracts/pull/454#issuecomment-2066899767

2024-04-19 17:08 UTC, Zitzak commented
I have removed the over-engineered directory structure with the PaymentClient as you suggested @marvinkruse

2024-04-23 08:14 UTC, FHieser approved these changes

2024-04-23 09:22 UTC, FHieser commented
In regard to the naming of the LM_PC_Bounty_v1.sol and LM_PC_Recurring_v1.sol 
Im fine with it, but I would recommend to change LM_PC_Recurring_v1 to LM_PC_RecurringPayment_v1

2024-04-23 09:26 UTC, marvinkruse commented
Shouldn't it then be "LM_PC_RecurringPayments_v1" instead of "LM_PC_RecurringPayment_v1"? As it's not just one payment?

2024-04-23 09:29 UTC, FHieser requested changes
Rename LM_PC_Recurring_v1.sol to LM_PC_RecurringPayments_v1.sol

2024-04-23 12:32 UTC, FHieser approved these changes

2024-04-23 13:37 UTC, marvinkruse commented
Besides the `Bounty` contract it looks good to me, can be merged if everyone else is happy. ✅ 

----

Only thing I found weird was that in the comments at the top of the contracts it says 
```
/**
 * @title   TransactionForwarder_v1: Transaction Forwarder v1 for Inverter Network.
 *
 * @notice  This contract enables users to interact with smart contracts indirectly through
 *          a trusted forwarder. It supports meta transactions, allowing transactions to be
 *          sent by one party but signed and paid for by another. It also handles batch
 *          transactions (multi-call), facilitating complex, multi-step interactions within a single
 *          transaction.
 *
 * @dev     Integrates {ERC2771Forwarder} and Context to manage and relay meta transactions.
 *          It handles nonce management, signature verification, and ensures only trusted calls
 *          are forwarded.
 *
 * @author  Inverter Network.
 */
```

I don't consider the name or title of the contract to be `TransactionForwarder_v1` but to be `TransactionForwarder`. To me, having the file name there looks weird. Also, repeating it twice there doesn't really make much sense and it's not how I have seen it being used elsewhere. Also the addendum of "for the Inverter Network" is redundant. I know that this is not something you (@Zitzak) did, just something I noticed now when looking at it. Also the dot at the end of the author feels off to me, as it's not a sentence. My ideal NatSpec would look like this:

```
/**
 * @title   Meta-Transaction & Multicall Forwarder
 *
 * @notice  This contract enables users to interact with smart contracts indirectly through
 *          a trusted forwarder. It supports meta-transactions, allowing transactions to be
 *          sent by one party but signed and paid for by another. It also handles batch
 *          transactions (multicall), facilitating complex, multi-step interactions within a single
 *          transaction.
 *
 * @dev     Integrates {ERC2771Forwarder} and {Context} to manage and relay meta transactions.
 *          It handles nonce management, signature verification, and ensures only trusted calls
 *          are forwarded.
 *
 * @author  Inverter Network
 */
```

Important note here, though, that I also realize: this is not directly relevant for the renaming PR here, so we could do these types of changes once the audit handover is fully done and handle it in a different PR. I would just love a bit more consistency in the Natspec before the launch.

2024-04-23 14:00 UTC, Zitzak commented
I have implemented these contract natspecs, so I would say that they are part of this renaming PR.

I do agree @marvinkruse  that the `@title` could be done better, and happy to change this. However I will need some help in finding a good title for the contracts, where there hasn't been one in the past that I might repurpose

2024-04-23 14:03 UTC, Zitzak commented
> I don't consider the name or title of the contract to be TransactionForwarder_v1 but to be TransactionForwarder.

One more question, did you mean that the name of the contract itself should also be changed such to remove the version? @marvinkruse

2024-04-23 14:03 UTC, marvinkruse commented
In the interest of time, let's merge this one if everything else is good, as the NatSpec will take a bit of time to get in and go through everything. Can happen later. That's my view at least.

2024-04-23 14:04 UTC, marvinkruse commented
> > I don't consider the name or title of the contract to be TransactionForwarder_v1 but to be TransactionForwarder.
> 
> One more question, did you mean that the name of the contract itself should also be changed such to remove the version? @marvinkruse

Sorry, was typing things up as I thought about it. I just meant the `_v1` part in the Contracts name **in the NatSpec**. Is that what your question was?

2024-04-23 14:08 UTC, Zitzak commented
Let me do a quick change to the contracts, and then we can merge it. Those would be
- remove the `.` at the end of author
- Use the old titles we had for the contracts that had them
- Remove the `for the inverter network`

2024-04-23 14:31 UTC, marvinkruse commented
If that doesn't take too much time then that's great, yeah!

2024-04-23 14:41 UTC, Zitzak commented
@marvinkruse  I've just put the name of the contract in the title of the contracts (except for the one you suggested for the Forwarder), as that seems to be as it was before.

2024-04-23 16:38 UTC, FHieser approved these changes
LGTM

2024-04-23 16:49 UTC, merged