Feat: Implement workflow mutability policy
InverterNetwork/contracts pull request #461
Opened 2024-05-03 08:59 UTC by Zitzak

## Implements
- https://linear.app/inverter/issue/SC-46/implement-workflow-mutability-policy

2024-05-03 12:19 UTC, marvinkruse commented
Just did a first pass over the implementation. Looks good to me! Will do a second pass within the next 30 minutes, but haven't found anything yet - just fyi.

2024-05-03 13:33 UTC, marvinkruse approved these changes
lgtm - good work! 🙏

2024-05-07 09:03 UTC, FHieser requested changes

2024-05-07 09:03 UTC, FHieser commented on src/orchestrator/Orchestrator_v1.sol
Is it possible to remove the Authorizer via the ModuleManager directly and therefor brick it?
We might wanna change that in this PR too

2024-05-07 11:03 UTC, Zitzak commented on src/orchestrator/Orchestrator_v1.sol
Just for my understanding, you mean that we can remove the authorizer through the ModuleManager -> (initiate)removeModule and then we wouldn't be able to call the functions within the Orchestrator anymore that require authentification. Is that correct? @FHieser

2024-05-07 13:49 UTC, marvinkruse commented on src/orchestrator/Orchestrator_v1.sol
Good point @FHieser - thanks for adding this @Zitzak! 🙏

2024-05-07 13:53 UTC, marvinkruse approved these changes
Good stuff, latest commit looks fine to me!

2024-05-07 14:24 UTC, FHieser approved these changes

2024-05-07 14:29 UTC, marvinkruse approved these changes

2024-05-07 15:08 UTC, merged