Expand payment order struct
InverterNetwork/contracts pull request #474
Opened 2024-05-20 10:06 UTC by 0xNuggan

2024-05-21 14:27 UTC, FHieser requested changes
All in all looks good
Minor changes needed

2024-05-21 14:27 UTC, FHieser commented on src/modules/logicModule/abstracts/ERC20PaymentClientBase_v1.sol
> +            _addPaymentOrder(currentOrder);
remove currentorder and go with orders[i] directly

2024-05-21 14:27 UTC, FHieser commented on src/modules/logicModule/abstracts/ERC20PaymentClientBase_v1.sol
> +        IERC20(token).safeIncreaseAllowance(address(spender), amount);
Didnt we talk about this being allowance should be upped to outstanding token amount?

2024-05-21 14:27 UTC, FHieser commented on src/modules/logicModule/abstracts/ERC20PaymentClientBase_v1.sol
>      /// @dev Ensures `amount` of payment tokens exist in address(this).
I would love a @dev comment here explaining what exactly is happening here

2024-05-21 14:27 UTC, FHieser commented on src/modules/logicModule/abstracts/ERC20PaymentClientBase_v1.sol
> +        address[] memory tokens_buffer = new address[](ordersLength);
I dont love this
How about we create a struct combination that allows to order the payment orders directly by token

For example:

struct paymentOrderCollection{
address token;
paymentOrders[] orders;
} 

That way you can actually keep the old Payment Order strcuture and you dont need special sorting of the different tokens. You would then basically only check when creating if a collection already exists for that token.
You could probably even optimize it with a mapping and array of current collections to look stuff up cheaper there

2024-05-21 14:27 UTC, FHieser commented on src/modules/logicModule/abstracts/ERC20PaymentClientBase_v1.sol
> +        address[] memory tokens_buffer = new address[](ordersLength);
We agreed together that we were gonna put this on the backlog due to time concerns
We will create a linear issue to rework this

2024-05-21 14:27 UTC, FHieser commented on test/modules/logicModule/oracle/OptimisticOracleIntegrator.t.sol
> +    /*
![pedro-pascal](https://github.com/InverterNetwork/contracts/assets/47272854/28a86675-97ad-45ab-b6c7-3ed8124236d5)

2024-05-22 09:27 UTC, 0xNuggan commented on src/modules/logicModule/abstracts/ERC20PaymentClientBase_v1.sol
> +        IERC20(token).safeIncreaseAllowance(address(spender), amount);
Changed it and updated test

2024-05-22 15:42 UTC, 0xNuggan commented on test/modules/logicModule/oracle/OptimisticOracleIntegrator.t.sol
> +    /*
![pedroPascal](https://github.com/InverterNetwork/contracts/assets/82726722/6001c6c6-1071-4060-9989-994eb027a737)

2024-05-23 07:57 UTC, FHieser approved these changes
LGTM

2024-05-23 08:13 UTC, merged