Sc 563 check governor eoa issue
InverterNetwork/contracts pull request #535
Opened 2024-06-06 14:54 UTC by FHieser

2024-06-07 11:34 UTC, 0xNuggan requested changes

2024-06-07 11:34 UTC, 0xNuggan commented on test/factories/ModuleFactory_v1.t.sol
> +    function testInitFailsForUnevenArrays(uint number1, uint number2) public {
I'd rename this to "testInitFailsForMismatchedArrayLenghts". "Uneven" sounds like "it should revert if the array length is 3"

2024-06-07 11:34 UTC, 0xNuggan commented
1 thing, rest looks good to me.

2024-06-08 15:47 UTC, marvinkruse approved these changes
Makes the deployment a lot easier in regards to the MultiSig, so makes sense to me. Looks good to me!

2024-06-08 15:48 UTC, marvinkruse commented
Just pushed a little fix, as the renamed test had a typo :D

2024-06-08 17:04 UTC, merged