[SC-640] Bug(64): Make asserter pay for the bond
InverterNetwork/contracts pull request #559
Opened 2024-07-04 10:42 UTC by 0xNuggan

Ensure that the `asserter` actually pays for the bond. Also added a specific error message and updated tests

2024-07-12 10:01 UTC, Zitzak requested changes
Not to familar with the OOI so good that MarvinK looks at it as well. Found 2 small things

2024-07-12 10:01 UTC, Zitzak commented on src/modules/logicModule/abstracts/oracleIntegrations/UMA_OptimisticOracleV3/OptimisticOracleIntegrator.sol
> +            (bool success, bytes memory data) = address(defaultCurrency).call(
`data` shadows exisiting declaration. Consider making the functiona parameter `_data`

2024-07-12 10:01 UTC, Zitzak commented on test/modules/logicModule/oracle/OptimisticOracleIntegrator.t.sol
> +        address who
unused variable

2024-07-12 10:06 UTC, Zitzak commented on src/modules/logicModule/abstracts/oracleIntegrations/UMA_OptimisticOracleV3/OptimisticOracleIntegrator.sol
> +            (bool success, bytes memory data) = address(defaultCurrency).call(
variable was actually contained within the else code block. Still updated it for readability and pushed the changes. Waiting for @marvinkruse review to finalize

2024-07-12 10:07 UTC, Zitzak commented
Added the change myself quickly @0xNuggan, jfyi

2024-07-12 10:07 UTC, Zitzak approved these changes

2024-07-12 10:11 UTC, marvinkruse requested changes
Otherwise good!

2024-07-12 10:11 UTC, marvinkruse commented on src/modules/logicModule/abstracts/oracleIntegrations/UMA_OptimisticOracleV3/OptimisticOracleIntegrator.sol
> +            //ensure we have enough balance
Whitespace between `//` and `ensure` is missing.

2024-07-12 10:11 UTC, marvinkruse commented on src/modules/logicModule/abstracts/oracleIntegrations/UMA_OptimisticOracleV3/OptimisticOracleIntegrator.sol
> +            //require(success && (data.length == 0 || abi.decode(data, (bool)))); -> taken over from SafeERC20 since we want to override the revert messsage
Whitespace between `//` and `require` is missing.

2024-07-12 10:14 UTC, 0xNuggan commented
Thanks for the reviews! Fixed the whitespace

2024-07-12 10:16 UTC, marvinkruse approved these changes
good work, gents 🙏

2024-07-12 11:41 UTC, 0xNuggan commented
While fixing bug 118 I noticed an edge case that's not covered here. Will update and reopen once I'm done there

2024-07-12 16:59 UTC, 0xNuggan commented
The case not covered was if the defaultBond token is not actually a contract. The added fix should address that

2024-07-12 17:16 UTC, Zitzak approved these changes
LGTM.

If we want to add additional check for it to be a token we could add a balance check as implemented here, not sure if needed here though
[[redo-sc-633-bug55-if-invertertransparentupgradeableproxy_v1-wont-not-be](https://github.com/InverterNetwork/contracts/blob/72210f82338e7170990f5287aed159e0c83dd87c/src/modules/authorizer/role/AUT_TokenGated_Roles_v1.sol#L135)](https://github.com/InverterNetwork/contracts/blob/72210f82338e7170990f5287aed159e0c83dd87c/src/modules/authorizer/role/AUT_TokenGated_Roles_v1.sol#L135)

2024-07-15 08:41 UTC, 0xNuggan commented
Yes! I do that in PR #600 for validation of paymentOrders() since I felt it was out of scope for this PR :)

2024-07-15 11:05 UTC, merged