[SC-690] feat: remove transferOrchestratorToken override
InverterNetwork/contracts pull request #563
Opened 2024-07-04 15:13 UTC by Zitzak

## What has been done?
- We have restructured the flow of how tokens get drawn from the FM. This resulted in that there is no need for the restriction anymore

2024-07-05 08:42 UTC, 0xNuggan requested changes
You can also remove the error defined in line 44. Apart from that, it looks good to me!

2024-07-08 11:23 UTC, Zitzak commented
That error is still being used by the override of function `mintIssuanceTokenTo` @0xNuggan :)
https://github.com/InverterNetwork/contracts/blob/4baafa12ce39696baa20be8c6977a6a8fa32e1cd/src/modules/fundingManager/bondingCurve/FM_BC_Restricted_Bancor_Redeeming_VirtualSupply_v1.sol#L87

2024-07-11 08:39 UTC, 0xNuggan approved these changes
You are absolutely right, I don't know how I missed that :)

2024-07-12 10:13 UTC, marvinkruse approved these changes

2024-07-12 10:25 UTC, merged