[SC-645] (Bug 75) LM_PC_KPIRewarder_v1: DoS vector if bond token has a blocklist and disputer set disputer address to a blocked address
InverterNetwork/contracts pull request #580
Opened 2024-07-09 12:54 UTC by 0xNuggan

**NOTE: New Version with corredct commit history**

## What has been done
- Added a onlyAdmin `deleteStuckAssertion()` function that allows removal of reverting assertion settlements. This function deletes local storage of the faulty assertion as if it had been asserted False and resests `asertionPending`
- Created tests for the new function

2024-07-09 14:47 UTC, FHieser commented on src/modules/logicModule/LM_PC_KPIRewarder_v1.sol
> +        // TODO make sure that the assertion has expired before trying to see if it settles (snippet below not working))
![ref-footballref](https://github.com/InverterNetwork/contracts/assets/47272854/e39ce559-d61b-4c4e-9d2e-f3c97633c0a3)

2024-07-09 14:50 UTC, FHieser requested changes
Im sorry xD

2024-07-09 14:53 UTC, 0xNuggan commented on src/modules/logicModule/LM_PC_KPIRewarder_v1.sol
> +        // TODO make sure that the assertion has expired before trying to see if it settles (snippet below not working))
lmao

2024-07-10 07:39 UTC, FHieser approved these changes
Left 1 comment

2024-07-10 07:39 UTC, FHieser commented on src/modules/logicModule/LM_PC_KPIRewarder_v1.sol
> +        uint assertionExpirationTime =
Why save into stack?

2024-07-11 07:23 UTC, merged