Make ERC20Issuance minting rights whitelist-based
InverterNetwork/contracts pull request #604
Opened 2024-07-15 16:13 UTC by 0xNuggan

## What has been done
- Substituted `address minter` with a mapping, so more than one address can mint.
- Expanded tests

2024-07-16 14:51 UTC, marvinkruse approved these changes
lgtm

2024-07-18 07:39 UTC, Zitzak requested changes
Reviewed this PR so I would understand the other one about the removing the deployment fromt he FM_BC init. Found some very minor stuff

2024-07-18 07:39 UTC, Zitzak commented on src/modules/fundingManager/bondingCurve/tokens/ERC20Issuance_v1.sol
>      /// @notice Sets the address of the minter.
This function now serves for setting and removing. Maybe adjust the comment to reflect that change?

2024-07-18 07:39 UTC, Zitzak commented on src/modules/fundingManager/bondingCurve/tokens/ERC20Issuance_v1.sol
>      /// @notice Sets the address of the minter.
Seeing that you also did that in the interface

2024-07-18 07:39 UTC, Zitzak commented on test/external/ERC20Issuance.t.sol
> +    └── It should set the new minter address rights
```suggestion
        └── It should set the new minter address rights
```

2024-07-18 07:39 UTC, Zitzak commented on test/external/ERC20Issuance.t.sol
> +        bool allowedBefore = token.allowedMinters(minter);
Unused variable

2024-07-18 07:55 UTC, Zitzak commented
I know in the case of paribu that they want to have the ability to mint new tokens directly, hence the added minter and the ownership of the token. However for other projects this might open the door to add new minters through a malicious owner of the contract without actually bricking the system, which would happen with other exploits where the owner has power over lets say changing a module.

So here are my questions:
1. Will we have an interface within our Control Room (or within the meme coin launcher for that matter) to deploy the issuance token such that we can pass the address as argument during FM_BC deployment. For Paribu I'm assuming this will just be a manual process right.
2. Might it make sense to suggest (either manually or within a Control Room flow) to pass ownership of the token to a multisig? 

@0xNuggan

2024-07-18 10:46 UTC, Zitzak approved these changes
LGTM. smart to make use of ERC20Capped as well as moving it to a different folder

2024-07-18 10:47 UTC, Zitzak commented
Apologies @marvinkruse, intended not to press the re-review button here

2024-07-18 10:57 UTC, marvinkruse commented
> Apologies @marvinkruse, intended not to press the re-review button here

all good, will just check it out anyways as I'm here :D

2024-07-18 12:32 UTC, marvinkruse approved these changes
lgtm, under the condition that the tests are not failing anymore :D

2024-07-19 11:25 UTC, merged